### ISSUE TITLE
Open to new Ideas

### ISSUE THREAD

**Issue by tanayag** [shitpy/shitpy#1]
I am open to new Ideas for shitpy.

some of the things I want to implement are

overload some functions in a very shitty manner, so that
>>> a = str(5)
>>> b = str(10)
>>> a + b
15
"and a hilarious message here"

for the start add a new folder shitpy and make python file name operators.py
implement a class to do above, that way u can complete ur PR for hacktober fest :)

**Comment by iordic** [comment]
I'll begin with something. I think function overload doesn't work in python. 😕

**Comment by iordic** [comment]
The messages can be randomly extracted from a json file or something like that.
What idea did u have about these?

**Comment by tanayag** [comment]
of course function overloading works in python, eg:

```
class int:
	def __init__(self,first):
		self.first = first
```
```
a=int(10)
print(a)  #check the results now
```
this will overload int function, similarly u can overload str, and implement required methods



if u want a head start with classes try [this](http://interactivepython.org/runestone/static/pythonds/Introduction/ObjectOrientedProgramminginPythonDefiningClasses.html)

**Comment by iordic** [comment]
👍

**Comment by fheee** [comment]
hellop;
should we(i, idk) add a 'shit' dataType or Structure?

**Comment by tanayag** [comment]
hello @fheee 
I was thinking of creating a folder with diseases and adding files like diarrhoea, piles, etc.
what say?? 
also suggest what should we put in there

also yeah we can add `shit` what do u want to put in that shit?

**Comment by tanayag** [comment]
@fheee I am closing this issue, as I have created a gitter chat for shitpy.
https://gitter.im/shitpy/Lobby
