### ISSUE TITLE
Design a Logo for ShitPy

### ISSUE THREAD

**Issue by tanayag** [shitpy/shitpy#3]
Logo should be a simple brown ice-cream scoop like structure, as the layers decent color changes to green and lower most layer consist of snake head. SHIT + PY :)

**Comment by gnuself** [comment]
Looks like someone got this with #8 .

**Comment by tanayag** [comment]
ya but issue is still open
I m up for improvements

**Comment by gnuself** [comment]
Ok, I'll give it a shot...

**Comment by gnuself** [comment]
Added something in #9 pull request.

**Comment by kapil0kumar** [comment]
hey
I want to work on this issue

**Comment by tanayag** [comment]
Thanks @kapil0kumar
